# Generated by Django 5.2.1 on 2025-05-19 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_username_user_address_user_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kalyanmandap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mandap_name', models.CharField(max_length=100)),
                ('Mandap_description', models.TextField()),
                ('mandap_availability', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Public Waste', 'Public Waste'), ('Private Waste', 'Private Waste')])),
                ('description', models.TextField()),
                ('waste_type', models.CharField()),
                ('waste_type_other', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('time_slot', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kalyanmandap_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kalyanmandap_images/')),
                ('Kalyanmandap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalyanmandap_images', to='myapp.kalyanmandap')),
            ],
        ),
        migrations.CreateModel(
            name='Request_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='request_images/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_images', to='myapp.requests')),
            ],
        ),
    ]
