# Generated by Django 5.2.1 on 2025-05-19 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_kalyanmandap_requests_kalyanmandap_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
