# Generated by Django 5.2.1 on 2025-05-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_requests_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kalyanmandap',
            old_name='Mandap_name',
            new_name='mandap_name',
        ),
        migrations.RemoveField(
            model_name='kalyanmandap',
            name='Mandap_description',
        ),
        migrations.AddField(
            model_name='kalyanmandap',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kalyanmandap',
            name='mandap_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kalyanmandap',
            name='mandap_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kalyanmandap',
            name='mandap_contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kalyanmandap',
            name='mandap_minimum_booking_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kalyanmandap',
            name='mandap_price_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kalyanmandap',
            name='mandap_price_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kalyanmandap',
            name='mandap_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kalyanmandap',
            name='mandap_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
