# Generated by Django 5.2.1 on 2025-05-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_mandap_name_kalyanmandap_mandap_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalyanmandap',
            name='mandap_availability',
        ),
    ]
