# Generated by Django 5.2.1 on 2025-05-19 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_kalyanmandap_mandap_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kalyanmandap_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=100)),
                ('number_of_people', models.IntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration', models.CharField(max_length=100)),
                ('additional_requests', models.TextField()),
                ('payment_method', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('kalyanmandap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalyanmandap_booking', to='myapp.kalyanmandap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalyanmandap_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
