# Generated by Django 5.2.1 on 2025-05-20 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_kalyanmandap_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='type',
            field=models.CharField(choices=[('Public Waste', 'Public Waste'), ('Personal Waste', 'Personal Waste')]),
        ),
        migrations.CreateModel(
            name='StatusUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusupdates', to='myapp.requests')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusupdates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
