# Generated by Django 5.2.1 on 2025-05-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_requests_address_requests_block_requests_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requests',
            name='waste_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
