# Generated by Django 5.2.1 on 2025-05-23 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_requests_type_alter_requests_waste_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_booking', to='myapp.requests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StatusUpdates',
        ),
    ]
