# Generated by Django 5.2.1 on 2025-05-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_request_booking_delete_statusupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalyanmandap_booking',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.DeleteModel(
            name='request_booking',
        ),
    ]
