# Generated by Django 5.2.1 on 2025-05-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_kalyanmandap_booking_comment_requests_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalyanmandap_booking',
            name='service_type',
            field=models.CharField(default='mandap booking'),
        ),
        migrations.AddField(
            model_name='requests',
            name='service_type',
            field=models.CharField(default='waste pickup'),
        ),
    ]
