# Generated by Django 5.2.1 on 2025-05-23 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_kalyanmandap_booking_service_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutionSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PollutionTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active_status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollutionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_source', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pollutionsubcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pollutiontypemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Pollution_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pollution_images/')),
                ('pollutionreport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollution_images', to='myapp.pollutionreport')),
            ],
        ),
        migrations.AddField(
            model_name='pollutionsubcategory',
            name='pollution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myapp.pollutiontypemaster'),
        ),
    ]
