# Generated by Django 5.2.1 on 2025-05-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_complaintcategory_pollutionreport_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='service_type',
            field=models.CharField(default='complaints'),
        ),
    ]
