# Generated by Django 5.2.1 on 2025-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_complaint_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('scheduled', 'scheduled'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='kalyanmandap_booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('scheduled', 'scheduled'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='pollutionreport',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('scheduled', 'scheduled'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('scheduled', 'scheduled'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
