# Generated by Django 5.2.1 on 2025-05-26 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_complaint_comment_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CesspoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('current_location', models.CharField(max_length=255)),
                ('full_address', models.TextField()),
                ('description', models.TextField()),
                ('waste_tank_type', models.CharField(max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('urgency_level', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_datetime', models.DateTimeField(blank=True, null=True)),
                ('accessibility_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CesspoolRequest_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cesspool_images/')),
                ('Cesspool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cesspool_images', to='myapp.cesspoolrequest')),
            ],
        ),
    ]
