# Generated by Django 5.2.1 on 2025-05-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_cesspoolrequest_cesspoolrequest_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cesspoolrequest',
            old_name='full_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='cesspoolrequest',
            old_name='current_location',
            new_name='location',
        ),
    ]
