# Generated by Django 5.2.1 on 2025-05-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_full_address_cesspoolrequest_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesspoolrequest_images',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
