# Generated by Django 5.2.1 on 2025-05-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_cesspoolrequest_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesspoolrequest',
            name='service_type',
            field=models.CharField(default='cesspool'),
        ),
    ]
