# Generated by Django 5.2.1 on 2025-05-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_cesspoolrequest_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesspoolrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cesspoolrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('scheduled', 'scheduled'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
