# Generated by Django 5.2.1 on 2025-05-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_cesspoolrequest_comment_cesspoolrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_images',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
